name: waveguide3
channels:
  - conda-forge
  - nvidia            # <-- comment out if no CUDA GPU
dependencies:
  # --- core numerics & QEC ---
  - python=3.11
  - numpy>=1.26
  - scipy>=1.12
  - pandas>=2.2
  - stim>=1.16            # fast Clifford simulator
  - pymatching>=2.1       # MWPM decoder
  - qutip                 # Lindbladian solver
  - qutip-gpu             # builds CUDA kernels if GPU present
  - pytorch::pytorch      # RL optimiser (Q-CAT)  (CPU build)
  - pytorch::pytorch-cuda   # uncomment for GPU build
  # --- plotting / notebooks ---
  - matplotlib
  - jupyterlab
  # --- dev / QA ---
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  - sphinx
  - sphinx_rtd_theme
  - latexmk                 # PDF build of manual
  # --- packaging & misc ---
  - git
  - git-lfs
  - pre-commit
  - pip
  - pip:
      - gymnasium           # RL environment wrapper
      - scikit-optimize     # GP-BO warm-start for Q-CAT
