name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: waveguide
          environment-file: environment.yml
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base latexmk
      - name: Run pytest
        run: pytest -q
      - name: Build manual
        run: latexmk -pdf docs/Waveguide_manual.tex
      - uses: actions/upload-artifact@v3
        with:
          name: manual
          path: docs/Waveguide_manual.pdf
